In [1]:
#Chapter 5 pandas 시작하기

In [1]:
# pandas import convention
from pandas import Series, DataFrame

In [2]:
import pandas as pd

In [3]:
import numpy as np

In [5]:
#5.1.1 Series
obj = Series([4,7,-5,3])

In [6]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [7]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [8]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [11]:
obj2 = Series([4,7,-5,3], index=['a','b','c','d'])

In [12]:
obj2

a    4
b    7
c   -5
d    3
dtype: int64

In [13]:
obj2['a']

4

In [14]:
obj2['d'] = 6

In [15]:
obj2

a    4
b    7
c   -5
d    6
dtype: int64

In [17]:
obj2[['c','a','d']]

c   -5
a    4
d    6
dtype: int64

In [18]:
obj2[obj2>0]

a    4
b    7
d    6
dtype: int64

In [19]:
obj2*2

a     8
b    14
c   -10
d    12
dtype: int64

In [20]:
np.exp(obj2)

a      54.598150
b    1096.633158
c       0.006738
d     403.428793
dtype: float64

In [21]:
'b' in obj2

True

In [22]:
'3' in obj2

False

In [23]:
#dict 객체에서 Series 객체 생성
sdata = {'Ohio':35000, 'Texas':71000, 'Oregon':16000, 'Utah':5000}

In [24]:
sdata

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [26]:
obj3 = Series(sdata)

In [27]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [36]:
states = ['California','Ohio','Oregon','Texas']

In [37]:
obj4 = Series(sdata, index=states)

In [38]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [39]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [40]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [41]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [42]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [43]:
obj4.name

In [44]:
obj4.name='population'

In [45]:
obj4.name

'population'

In [46]:
obj4.index.name

In [47]:
obj4.index.name='state'

In [48]:
obj4.index.name

'state'

In [49]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [50]:
obj.index = ['Bob','Steve','Jeff','Ryan']

In [51]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [52]:
obj.index.name

In [53]:
#DataFrame

In [58]:
data = {'state':['Ohio','Ohio','Ohio','Nevada','Nevada'],
       'year':[2000,2001,2002,2001,2002],
       'pop':[1.5,1.7,3.6,2.4,2.9]}

In [59]:
data

{'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002],
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}

In [60]:
frame = DataFrame(data)

In [61]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [62]:
DataFrame(data, columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [64]:
frame2 = DataFrame(data, columns=['year','state','pop','debt'], index=['one','two','three','four','five'])

In [65]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [66]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [67]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [68]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [70]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [71]:
frame2['debt'] = 16.5

In [72]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [73]:
np.arange(5.)

array([0., 1., 2., 3., 4.])

In [74]:
frame2['debt'] = np.arange(5.)

In [75]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

In [76]:
val=Series([-1.2, -1.5, -1.7], index = ['two','four','five'])

In [77]:
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [78]:
frame2['debt'] = val

In [80]:
#frame2['debt']의 원래 값은 모두 지워진다
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [81]:
frame2['eastern'] = frame2.state=='ohio'

In [82]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN    False
two    2001    Ohio  1.7  -1.2    False
three  2002    Ohio  3.6   NaN    False
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False

In [83]:
del frame2['eastern']

In [84]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [85]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [86]:
pop = {'Nevada':{2001:2.4, 2002:2.9},
      'Ohio':{2000:1.5, 2001:1.7, 2002:3.6}}

In [87]:
pop

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [88]:
frame3 = DataFrame(pop)

In [89]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [90]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [91]:
DataFrame(pop, index = [2001,2002, 2003])

AttributeError: 'list' object has no attribute 'astype'

In [92]:
pdata = {'Ohio':frame3['Ohio'][:-1],
        'Nevada':frame3['Nevada'][:2]}

In [93]:
pdata

{'Ohio': 2000    1.5
 2001    1.7
 Name: Ohio, dtype: float64, 'Nevada': 2000    NaN
 2001    2.4
 Name: Nevada, dtype: float64}

In [94]:
DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [95]:
frame3.index.name = 'year'

In [96]:
frame3.columns.name = 'state'

In [97]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [98]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [99]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7]], dtype=object)

In [100]:
#5.1.3 index object

In [102]:
range(3)

range(0, 3)

In [103]:
obj = Series(range(3), index=['a','b','c'])

In [104]:
obj.index

Index(['a', 'b', 'c'], dtype='object')

In [105]:
index = obj.index

In [106]:
index

Index(['a', 'b', 'c'], dtype='object')

In [107]:
index[1:]

Index(['b', 'c'], dtype='object')

In [108]:
index[1]

'b'

In [109]:
index[1] = 'b'

TypeError: Index does not support mutable operations

In [110]:
index = pd.Index(np.arange(3))

In [111]:
index

Int64Index([0, 1, 2], dtype='int64')

In [112]:
obj2 = Series([1.5, -2.5, 0], index = index)

In [113]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [114]:
obj2.index is index

True

In [115]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [116]:
'Ohio' in frame3.columns

True

In [117]:
2003 in frame3.index

False

In [118]:
obj = Series([4.5, 7.2, -5.3, 3.6], index = ['d','b','a','c'])

In [119]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [120]:
obj2 = obj.reindex(['a','b','c','d','e'])

In [121]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [123]:
obj.reindex(['a','b','c','d','e'], fill_value=0)

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [124]:
obj3 = Series(['blue','purple','yellow'], index=[0,2,4])

In [125]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [126]:
obj3.reindex(range(6), method = 'ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [127]:
frame = DataFrame(np.arange(9).reshape((3,3)))

In [128]:
frame

0  1  2
0  0  1  2
1  3  4  5
2  6  7  8

In [131]:
#row, column 둘 다 reindex 가능
frame = DataFrame(np.arange(9).reshape((3,3)), index = ['a','c','d'], columns=['Ohio','Texas','California'])

In [130]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [132]:
frame2 = frame.reindex(['a','b','c','d'])

In [133]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [134]:
states = ['Texas','Utah','California']

In [135]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [138]:
frame.reindex(index=['a','b','c','d'],method='ffill',columns = states)

ValueError: index must be monotonic increasing or decreasing

In [139]:
#5.2.2  delete row, columns

In [140]:
obj = Series(np.arange(5.), index=['a','b','c','d','e'])

In [141]:
new_obj = obj.drop('c')

In [142]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [147]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [148]:
#delete value

In [149]:
data = DataFrame(np.arange(16).reshape((4,4)), index = ['Ohio','Colorado','Utah','NewYork'],columns=['one','two','three','four'])

In [150]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
NewYork    12   13     14    15

In [151]:
data.drop(['Colorado','Ohio']) #axis=0

one  two  three  four
Utah       8    9     10    11
NewYork   12   13     14    15

In [160]:
data.drop('two',axis=1)

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
NewYork    12   13     14    15

In [161]:
#5.2.3 색인하기, 선택하기, 거르기
obj=Series(np.arange(4.), index=['a','b','c','d'])

In [162]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [163]:
obj['b']

1.0

In [165]:
obj[1]

1.0

In [166]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [169]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [170]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [171]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [172]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [173]:
obj['b':'c']=5

In [174]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [175]:
data=DataFrame(np.arange(16).reshape((4,4)),
              index=['Ohio','Colorado','Utah','NewYork'],
              columns=['one','two','three','four'])

In [176]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
NewYork    12   13     14    15

In [177]:
data['two']

Ohio         1
Colorado     5
Utah         9
NewYork     13
Name: two, dtype: int32

In [178]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
NewYork      14   12

In [179]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [180]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
NewYork    12   13     14    15

In [181]:
data['three']>5

Ohio        False
Colorado     True
Utah         True
NewYork      True
Name: three, dtype: bool

In [185]:
data[[False,True,True,True]]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
NewYork    12   13     14    15

In [186]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
NewYork   False  False  False  False

In [188]:
data[data<5]

one  two  three  four
Ohio      0.0  1.0    2.0   3.0
Colorado  4.0  NaN    NaN   NaN
Utah      NaN  NaN    NaN   NaN
NewYork   NaN  NaN    NaN   NaN

In [189]:
data[data<5]=0

In [190]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
NewYork    12   13     14    15

In [191]:
#5.2.4 산술연산과 데이터 정렬

In [192]:
s1 = Series([7.3, -2.5, 3.4, 1.5], index = ['a','c','d','e'])
s2 = Series([-2.1,3.6,-1.5,4,3.1], index = ['a','c','e','f','g'])

In [193]:
s1,s2

(a    7.3
 c   -2.5
 d    3.4
 e    1.5
 dtype: float64, a   -2.1
 c    3.6
 e   -1.5
 f    4.0
 g    3.1
 dtype: float64)

In [194]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [195]:
s1.add(s2, fill_value=0)

a    5.2
c    1.1
d    3.4
e    0.0
f    4.0
g    3.1
dtype: float64

In [196]:
df1 = DataFrame(np.arange(9.).reshape((3,3)), columns=list('bcd'), index=['Ohio','Texas','Colorado'])

In [197]:
df2 = DataFrame(np.arange(12.).reshape((4,3)), columns=list('bde'), index=['Utah','Ohio','Texas','Oregon'])

In [198]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [199]:
df1.add(df2, fill_value=0)

b    c     d     e
Colorado  6.0  7.0   8.0   NaN
Ohio      3.0  1.0   6.0   5.0
Oregon    9.0  NaN  10.0  11.0
Texas     9.0  4.0  12.0   8.0
Utah      0.0  NaN   1.0   2.0

In [200]:
df2.add(df1, fill_value=0)

b    c     d     e
Colorado  6.0  7.0   8.0   NaN
Ohio      3.0  1.0   6.0   5.0
Oregon    9.0  NaN  10.0  11.0
Texas     9.0  4.0  12.0   8.0
Utah      0.0  NaN   1.0   2.0

In [201]:
#DataFrame과 Series간의 연산

In [202]:
arr = np.arange(12.).reshape((3,4))

In [203]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [204]:
arr[0]

array([0., 1., 2., 3.])

In [205]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [206]:
frame = DataFrame(np.arange(12.).reshape((4,3)), columns=list('bde'), index=['Utah','Ohio','Texas','Oregon'])

In [209]:
frame.iloc[0]

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [210]:
series = frame.iloc[0]

In [211]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [212]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [213]:
series2 = Series(range(3), index=['b','e','f'])

In [214]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [215]:
#row에 대해 연산하고자 할 경우
series3 = frame['d']

In [216]:
frame.sub(series3, axis=0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [217]:
#5.2.5 함수 적용과 맵핑

In [1]:
#5.3.1 상관관계와 공분산
import pandas as pd

In [6]:
import pandas_datareader.data as web

In [7]:
all_data = {ticker:web.get_data_yahoo(ticker)
           for ticker in ['AAPL','IBM','MSFT','GOOG']}

In [8]:
price = pd.DataFrame({ticker: data['Adj Close']
                     for ticker, data in all_data.items()})

In [25]:
volume = pd.DataFrame({ticker: data['Volume']
                      for ticker, data in all_data.items()})

In [13]:
returns = price.pct_change()

In [14]:
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2018-10-15 -0.021386  0.001988 -0.017979 -0.016062
2018-10-16  0.022037  0.028272  0.031599  0.026578
2018-10-17 -0.004321 -0.076282 -0.002613 -0.004985
2018-10-18 -0.023374 -0.026110 -0.019962 -0.024846
2018-10-19  0.015230 -0.011107  0.001475  0.007804

In [16]:
returns['MSFT'].corr(returns['IBM'])

0.47298182876675615

In [17]:
returns['MSFT'].cov(returns['IBM'])

8.089562542018828e-05

In [18]:
returns.MSFT.corr(returns.IBM)

0.47298182876675615

In [19]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.358415  0.420681  0.432866
IBM   0.358415  1.000000  0.472982  0.396265
MSFT  0.420681  0.472982  1.000000  0.513893
GOOG  0.432866  0.396265  0.513893  1.000000

In [20]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000256  0.000069  0.000095  0.000105
IBM   0.000069  0.000146  0.000081  0.000073
MSFT  0.000095  0.000081  0.000201  0.000111
GOOG  0.000105  0.000073  0.000111  0.000231

In [21]:
returns.corrwith(returns.IBM)

AAPL    0.358415
IBM     1.000000
MSFT    0.472982
GOOG    0.396265
dtype: float64

In [26]:
returns.corrwith(volume)

AAPL   -0.063227
IBM    -0.174045
MSFT   -0.087090
GOOG   -0.017141
dtype: float64

In [5]:
obj = pd.Series(['c','a','d','a','a','b','b','c','c'])

In [6]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [7]:
uniques = obj.unique()

In [8]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [9]:
obj.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

In [10]:
#value_counts 메서드는 pandas최상위 메서드, 어떤 배열이나 순차 자료 구조에서도 사용 가능
pd.value_counts(obj.values, sort=False)

c    3
b    2
d    1
a    3
dtype: int64

In [12]:
mask = obj.isin(['b','c'])

In [13]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

obj[mask]

In [14]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [ ]:
data = DataFrame({'Qu1':[1,3,4,3,4],
                 'Qu2':[2,3,1,2,3],
                  'Qu3':[1,5,2,4,4]})

In [20]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [18]:
result = data.apply(pd.value_counts).fillna(0)

In [19]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

In [21]:
#5.4 누락된 데이터 처리하기
string_data = Series(['aardvark','artichoke', np.nan, 'avocado'])

In [22]:
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [23]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [24]:
string_data[0] = None

In [25]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [26]:
from numpy import nan as NA

In [27]:
data = Series([1,NA, 3.5, NA, 7])

In [28]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [29]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [30]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [31]:
data = DataFrame([[1., 6.5, 3.], [1., NA, NA],
                 [NA, NA, NA], [NA, 6.5, 3.]])

In [32]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [33]:
cleaned = data.dropna()

In [34]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [35]:
data.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [36]:
data.dropna(how='all', axis=1)

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [49]:
#몇 개 이상 값이 있을 때만 살펴보고 싶다
df = DataFrame(np.random.randn(7,3))

In [50]:
df

0         1         2
0 -1.192468  0.419461 -0.941796
1  1.398870  0.299422 -0.680436
2  0.919612  0.941925 -0.528466
3  0.066248 -0.457449 -0.190359
4 -1.555649 -0.729016  0.634680
5 -0.434840  0.838056  1.831629
6 -1.148501 -0.190235 -0.672696

In [51]:
df.iloc[ :4, 1] = NA

In [52]:
df

0         1         2
0 -1.192468       NaN -0.941796
1  1.398870       NaN -0.680436
2  0.919612       NaN -0.528466
3  0.066248       NaN -0.190359
4 -1.555649 -0.729016  0.634680
5 -0.434840  0.838056  1.831629
6 -1.148501 -0.190235 -0.672696

In [53]:
df.iloc[:2, 2] = NA

In [54]:
df

0         1         2
0 -1.192468       NaN       NaN
1  1.398870       NaN       NaN
2  0.919612       NaN -0.528466
3  0.066248       NaN -0.190359
4 -1.555649 -0.729016  0.634680
5 -0.434840  0.838056  1.831629
6 -1.148501 -0.190235 -0.672696

In [55]:
df.dropna(thresh=3) #3개 이상 값이 있는 경우

0         1         2
4 -1.555649 -0.729016  0.634680
5 -0.434840  0.838056  1.831629
6 -1.148501 -0.190235 -0.672696

In [56]:
df.fillna(0)

0         1         2
0 -1.192468  0.000000  0.000000
1  1.398870  0.000000  0.000000
2  0.919612  0.000000 -0.528466
3  0.066248  0.000000 -0.190359
4 -1.555649 -0.729016  0.634680
5 -0.434840  0.838056  1.831629
6 -1.148501 -0.190235 -0.672696

In [57]:
df

0         1         2
0 -1.192468       NaN       NaN
1  1.398870       NaN       NaN
2  0.919612       NaN -0.528466
3  0.066248       NaN -0.190359
4 -1.555649 -0.729016  0.634680
5 -0.434840  0.838056  1.831629
6 -1.148501 -0.190235 -0.672696

In [58]:
df.fillna({1: 0.5, 2: -1})

0         1         2
0 -1.192468  0.500000 -1.000000
1  1.398870  0.500000 -1.000000
2  0.919612  0.500000 -0.528466
3  0.066248  0.500000 -0.190359
4 -1.555649 -0.729016  0.634680
5 -0.434840  0.838056  1.831629
6 -1.148501 -0.190235 -0.672696

In [59]:
df #원래 df 객체는 변하지 않음

0         1         2
0 -1.192468       NaN       NaN
1  1.398870       NaN       NaN
2  0.919612       NaN -0.528466
3  0.066248       NaN -0.190359
4 -1.555649 -0.729016  0.634680
5 -0.434840  0.838056  1.831629
6 -1.148501 -0.190235 -0.672696

In [60]:
 _ = df.fillna(0, inplace = True) #원래 df 객체를 변경

In [61]:
df

0         1         2
0 -1.192468  0.000000  0.000000
1  1.398870  0.000000  0.000000
2  0.919612  0.000000 -0.528466
3  0.066248  0.000000 -0.190359
4 -1.555649 -0.729016  0.634680
5 -0.434840  0.838056  1.831629
6 -1.148501 -0.190235 -0.672696

In [62]:
#보간 메서드 (ffil, bfil) fronfill? belowfill??
df = DataFrame(np.random.randn(6,3))

In [63]:
df

0         1         2
0 -1.205358  0.752641  1.007944
1 -0.902239 -1.223363 -2.688186
2 -1.270113  0.015697  0.716430
3 -0.275037 -0.112160 -2.139030
4  0.948366  0.621927 -0.099562
5 -1.098948  1.895670  1.374493

In [64]:
df.iloc[2: ,1] = NA; df.iloc[4: ,2] = NA

In [65]:
df

0         1         2
0 -1.205358  0.752641  1.007944
1 -0.902239 -1.223363 -2.688186
2 -1.270113       NaN  0.716430
3 -0.275037       NaN -2.139030
4  0.948366       NaN       NaN
5 -1.098948       NaN       NaN

In [66]:
df.fillna(method='ffill')

0         1         2
0 -1.205358  0.752641  1.007944
1 -0.902239 -1.223363 -2.688186
2 -1.270113 -1.223363  0.716430
3 -0.275037 -1.223363 -2.139030
4  0.948366 -1.223363 -2.139030
5 -1.098948 -1.223363 -2.139030

In [67]:
df.fillna(method='ffill', limit=2) #앞에서 2개까지만 채운다 

0         1         2
0 -1.205358  0.752641  1.007944
1 -0.902239 -1.223363 -2.688186
2 -1.270113 -1.223363  0.716430
3 -0.275037 -1.223363 -2.139030
4  0.948366       NaN -2.139030
5 -1.098948       NaN -2.139030

In [68]:
data = Series([1., NA, 3.5, NA, 7])

In [69]:
data.fillna(data.mean()) #NA를 평균으로 대체

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [71]:
data = Series(np.random.randn(10), index = [['a','a','a','b','b','b','c','c','d','d'],
                                           [1,2,3,1,2,3,1,2,2,3]])

In [72]:
data

a  1   -1.685274
   2   -0.829184
   3    0.661858
b  1   -0.384465
   2   -0.596521
   3    0.654437
c  1   -0.541031
   2    0.274578
d  2   -1.246897
   3    0.798155
dtype: float64

In [73]:
data.index

MultiIndex(levels=[['a', 'b', 'c', 'd'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1, 2, 2, 3, 3], [0, 1, 2, 0, 1, 2, 0, 1, 1, 2]])

In [74]:
data['b']

1   -0.384465
2   -0.596521
3    0.654437
dtype: float64

In [75]:
data['b':'c']

b  1   -0.384465
   2   -0.596521
   3    0.654437
c  1   -0.541031
   2    0.274578
dtype: float64

In [78]:
data.loc[['b','d']]

b  1   -0.384465
   2   -0.596521
   3    0.654437
d  2   -1.246897
   3    0.798155
dtype: float64

In [79]:
data[:, 2]

a   -0.829184
b   -0.596521
c    0.274578
d   -1.246897
dtype: float64

In [80]:
data.unstack()

1         2         3
a -1.685274 -0.829184  0.661858
b -0.384465 -0.596521  0.654437
c -0.541031  0.274578       NaN
d       NaN -1.246897  0.798155

In [81]:
type(data)

pandas.core.series.Series

In [82]:
data.unstack().stack()

a  1   -1.685274
   2   -0.829184
   3    0.661858
b  1   -0.384465
   2   -0.596521
   3    0.654437
c  1   -0.541031
   2    0.274578
d  2   -1.246897
   3    0.798155
dtype: float64

In [4]:
frame = DataFrame(np.arange(12).reshape((4,3)),
                 index=[['a','a','b','b'], [1,2,1,2]],
                 columns=[['Ohio','Ohio','Colorado'],
                          ['Green','Red','Green']])

In [5]:
frame

Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [6]:
frame.index.names=['key1','key2']; frame.columns.names=['state','color']

In [7]:
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [90]:
MultiIndex.from_arrays([['Ohio','Ohio','Colorado'], ['Green','Red','Green']], names=['state','color'])

NameError: name 'MultiIndex' is not defined

In [8]:
#5.5.1 계층순서 바꾸고 정렬하기
frame.swaplevel('key1','key2')

state      Ohio     Colorado
color     Green Red    Green
key2 key1                   
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

In [92]:
frame.sortlevel(1)

C:\Users\gjkim\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: sortlevel is deprecated, use sort_index(level= ...)
  """Entry point for launching an IPython kernel.


state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
b    1        6   7        8
a    2        3   4        5
b    2        9  10       11

In [93]:
frame.swaplevel(0,1).sortlevel(0)

C:\Users\gjkim\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: sortlevel is deprecated, use sort_index(level= ...)
  """Entry point for launching an IPython kernel.


state      Ohio     Colorado
color     Green Red    Green
key2 key1                   
1    a        0   1        2
     b        6   7        8
2    a        3   4        5
     b        9  10       11

In [9]:
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [10]:
frame.sum(level='key2')

state  Ohio     Colorado
color Green Red    Green
key2                    
1         6   8       10
2        12  14       16

In [11]:
frame.sum(level='key1')

state  Ohio     Colorado
color Green Red    Green
key1                    
a         3   5        7
b        15  17       19

In [13]:
frame.sum(level='color', axis=1)

color      Green  Red
key1 key2            
a    1         2    1
     2         8    4
b    1        14    7
     2        20   10

In [14]:
#5.5.3 DataFrame의 칼럼 사용하기

In [15]:
frame = DataFrame({'a':range(7), 'b':range(7,0,-1),
                  'c':['one','one','one','two','two','two','two'],
                  'd':[0,1,2,0,1,2,3]})

In [16]:
frame

a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [17]:
frame2 = frame.set_index(['c','d'])

In [18]:
frame2

a  b
c   d      
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [19]:
frame.set_index(['c','d'], drop=False)

a  b    c  d
c   d              
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

In [20]:
frame2.reset_index()

c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1

In [21]:
#5.6.1 정수색인
ser = Series(np.arange(3.))

In [22]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [23]:
ser[-1]

KeyError: -1

In [24]:
#6.1 Text파일 이용